name: Auto Trade Bot My Wallet v2

on:
  workflow_dispatch: {}  # Permite ejecución manual desde GitHub
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Trading Bot
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          NEXT_PUBLIC_BINANCE_API_URL: ${{ secrets.NEXT_PUBLIC_BINANCE_API_URL }}
        run: node trade-bot.js

      - name: Commit updated history.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/history.json
          git commit -m "📈 Actualiza historial de operaciones"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
